name: Metrics
on:
  schedule: [{ cron: "0 0 * * 1" }] # every Monday
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_followup: yes
          plugin_lines: yes
          plugin_achievements: yes
